### ISSUE TITLE
Layout quebrado para a grid 'Pagamento' - Tela 'Detalhes da Encomenda'

### ISSUE THREAD

**Issue by eduardopc** [payu-br/prestashop-transparente#4]
Na tela onde há as informações da Encomenda, os dados da grid 'Pagamento' se encontram quebrados.

![image](https://cloud.githubusercontent.com/assets/14925513/10346330/0d23efe0-6d05-11e5-9876-034a49a92905.png)

**Comment by Delorien** [comment]
Não inerente ao projeto.
